### ISSUE TITLE
Support custom avatar pictures

### ISSUE THREAD

**Issue by onny** [christophery/geist#10]
Hey,
I tried to change the avatar picture with wp-user-avatar but this doesn't seem to have an effect on the profile picture in the theme. Is it possible to customize this?

Regards
Jonas

**Comment by christophery** [comment]
This theme is using the standard [get_avatar()](https://developer.wordpress.org/reference/functions/get_avatar/) WordPress function, in theory your plugin should work with this theme.

By default this theme supports using custom avatars using [Gravatar](http://en.gravatar.com/) as it is built into WordPress itself.

I suggest following the steps listed in the [plugins FAQ](https://en-ca.wordpress.org/plugins/wp-user-avatar/#how%20do%20i%20use%20wp%20user%20avatar%3F).

**Comment by onny** [comment]
Thanks I solved the problem by enabling avatars in the settings area. Sorry my fault :/
