### ISSUE TITLE
Comments are closed - needs some styling

### ISSUE THREAD

**Issue by christophery** [christophery/geist#16]
Needs some minor styling. Perhaps centering the text and **bolding** it will help. 👍

See example here (scroll to bottom of comments): https://chrisyee.ca/blog/off-canvas-navigation/

<img width="1102" alt="Screen Shot 2020-08-20 at 12 13 37 PM" src="https://user-images.githubusercontent.com/1683361/90797418-9c3bc000-e2de-11ea-960b-5545dcde0f3e.png">

**Comment by h-shams** [comment]
hi @christophery, may i work on this?

**Comment by christophery** [comment]
@h-shams Sure!
