### ISSUE TITLE
Styling issue with avatar after single-page content

### ISSUE THREAD

**Issue by onny** [christophery/geist#17]
Hey,
I'm using the latest ''geist'' version (1.1.5)  on my blog (thanks so much for this template ;)). It looks like the styling is a bit broken for avatar profile pictures (see https://blog.project-insanity.org/2020/09/24/10-unoffical-nixos-packages-worth-checking-out/ ):

![2020-09-30-180615_grim](https://user-images.githubusercontent.com/757752/94710985-0b252380-0337-11eb-8a3b-bcc7c45f7c1b.png)

In the original Ghost 2.0 template the styling looks a bit different (see https://thomasehardt.com/welcome/ ):

![2020-09-30-181239_grim](https://user-images.githubusercontent.com/757752/94711777-1a58a100-0338-11eb-8a65-6709d01a28fe.png)

It's not a big thing but it would look better :)

Best regards
Jonas

**Comment by christophery** [comment]
Hi Jonas,

Good catch!

At first glance, this issue may be a conflict with a plugin you are using ([WP User Avatar](https://en-ca.wordpress.org/plugins/wp-user-avatar/)). What's happening is the CSS class of `author-profile-image` isn't being applied to the image.

This shouldn't be too hard to fix but will require me to investigate it further.

Cheers.

**Comment by onny** [comment]
Thanks for the hint. This could be the issue here.
Might also affect the user page / posts by user category:

![2020-10-01-094926_grim](https://user-images.githubusercontent.com/757752/94782436-bcb96880-03ba-11eb-88b1-cfe271462be0.png)

https://blog.project-insanity.org/author/onny/

Sorry for submitting a bug related to a custom plugin :/ But I really wanted to use locally uploaded avatars instead of external services ;)

Cheers

**Comment by christophery** [comment]
Fixed with [1.1.6](https://github.com/christophery/geist/releases/tag/1.1.6)

**Comment by onny** [comment]
Great thank you!
