### ISSUE TITLE
Paragraph Font Size

### ISSUE THREAD

**Issue by animemoeus** [christophery/geist#21]
All first paragraph in posts are to big, how can I make they're looks normal?

![Screenshot_20201003_192922](https://user-images.githubusercontent.com/33395829/94990446-c60b2680-05ae-11eb-9629-7007f5c9fb0c.png)

**Comment by christophery** [comment]
You can adjust the CSS styling of the first paragraph in a post by using this CSS selector: 

`.single-post .post-content>p:first-child`

The recommended way to edit the theme is to create a [child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/).
